version: '3.0'

services:
    api_gateway:
        image: king7282/everyportfolio:api_gateway
        ports:
            - "80:8080"
        depends_on:
            - redis
            - nginx
    user:
        image: king7282/everyportfolio:user
        volumes:
            - d:/properties:/etc/properties
        depends_on:
            - redis
    portfolio:
        image: king7282/everyportfolio:portfolio
        volumes:
            - d:/properties:/etc/properties
    redis:
        image: redis
        volumes:
            - c:/redis.conf:/usr/local/etc/redis/redis.conf
    nginx:
        image: nginx